name: 'Setup Dockem'
description: 'Sets up the dockem cli for use in your actions'
runs:
  using: "composite"
  steps:
    - name: Pull the dockem binary
      run: |
        # First we need to get is this is amd64 or arm64
        if [[ "$(uname -m)" == "x86_64" ]]; then
          curl -L -o dockem https://github.com/kerren/dockem/releases/download/v2.1.0/dockem-v2.1.0-linux-amd64
        else
          curl -L -o dockem https://github.com/kerren/dockem/releases/download/v2.1.0/dockem-v2.1.0-linux-arm64
        fi
        chmod +x dockem
      shell: bash

    - name: Add the dockem binary to the path
      run: |
        set -x
        echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}