name: 'Setup Dockem-RS'
description: 'Sets up the dockem-rs cli for use in your actions'
author: 'Lynch Mwaniki'
branding:
  icon: 'terminal'
  color: 'gray-dark'
runs:
  using: "composite"
  steps:
    - name: Pull the dockem-rs binary
      run: |
        cd "$GITHUB_ACTION_PATH"
        # First we need to get is this is x86_64 or aarch64
        if [[ "$(uname -m)" == "x86_64" ]]; then
          wget https://github.com/LynchSKM/dockem-rs/releases/download/v1.0.5/dockem-rs-v1.0.5-linux-x86_64
          chmod +x dockem-rs-v1.0.5-linux-x86_64
          mv dockem-rs-v1.0.5-linux-x86_64 dockem-rs
        else
          wget https://github.com/LynchSKM/dockem-rs/releases/download/v1.0.5/dockem-rs-v1.0.5-linux-aarch64
          chmod +x dockem-rs-v1.0.5-linux-aarch64
          mv dockem-rs-v1.0.5-linux-aarch64 dockem-rs
        fi
      shell: bash

    - name: Add the dockem-rs binary to the path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
