name: "Run Action"

on:
  push:
    branches:
      - main
      - develop

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dockem
        uses: kerren/setup-dockem@v2

      - name: Run Dockem
        run: dockem --version