name: "Run Action"

on:
  push:
    branches:
      - main
      - develop

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dockem
        uses: kerren/setup-dockem@v1.0.3

      - name: Run Dockem
        run: |
          set -x
          echo $PATH
          ls -lah /home/runner/work/_actions/kerren/setup-dockem/v1.0.3
          dockem --version